# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NowyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst', models.CharField(max_length=200)),
                ('publication_date', models.DateTimeField(verbose_name='date')),
            ],
        ),
    ]
